name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: install software
      run: |
        ./tools/update-tools.sh

    - name: build
      run: |
        export PATH=./tools/zig:$PATH
        .github/workflows/build.sh
